[package]
name = "osu2itg"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30.0"
native-windows-derive = "1.0.5"
native-windows-gui = "1.0.13"
num = "0.4"
rand = "0.8.5"
rfd = "0.15.2"
